#!/bin/sh
flatpak install --system --bundle /usr/share/deepin-flatpak/app/com.deepin.ImageViewer/x86_64/master/bundle
rm /usr/share/deepin-flatpak/app/com.deepin.ImageViewer/x86_64/master/bundle
for f in `ls -d /home/*/`;
do
	mkdir -p $f/.var/app/com.deepin.ImageViewer/cache/;
	USER=`echo $f|cut -d '/' -f 3`;
	chown -R $USER:$USER $f
	tar -zxf /usr/share/deepin-flatpak/runtime/com.deepin.Platform/x86_64/15.5/fontconfig.tar.gz -C $f.var/app/com.deepin.ImageViewer/cache/
done


exit 0
